### PR TITLE
fix for unfetter-discover/unfetter#1095

### LINKED ISSUE #1095: Summary Page 'most vulnerable' is blank
I upgraded from the previous version of Unfetter (0.3.6)

The Assessments already created have an empty "where you are most vulnerable"

image

### PR DESCRIPTION
**Pull request by mushinlogit**
fixes unfetter-discover/unfetter#1095
we can merge into develop, then repush the 0.3.7 branch, since no other changes were made

## problem
v2 assessments summary shows empty panel

## changes
update ordering of results array to result types

## test
pull this PR
visit the v2 assessments summary panel for 'indicators', 'mitigations', and 'sensors' ensure the top right panel is populated

### CODE REVIEW

File: unfetter-discover-api/api/controllers/x_unfetter_assessments.js [hunk 1]
```diff
@@ -214,27 +214,30 @@ const riskPerKillChain = controller.getByIdCb((err, result, req, res, id) => { /
                 assessment = assessment.toObject().stix;
             }
 
-            const indicators = results[0]
+            const courseOfActions = results[0]
```
Comment (webiator) [inline unfetter-discover-api/api/controllers/x_unfetter_assessments.js]: Should this be `courseOfActions` or `coursesOfAction`?

File: unfetter-discover-api/api/controllers/x_unfetter_assessments.js [hunk 2]
```diff
@@ -214,27 +214,30 @@ const riskPerKillChain = controller.getByIdCb((err, result, req, res, id) => { /
...
                 .filter(doc => doc !== undefined)
                 .map(doc => ({
                     ...doc.toObject().stix,
                     ...doc.toObject().metaProperties
                 }));
-            const indicatorRisks = [];
-            const sensors = results[1]
+            const coaRisks = [];
```
Comment (webiator) [inline unfetter-discover-api/api/controllers/x_unfetter_assessments.js]: Based on previous question and other `Risks` variable names below, maybe `courseRisks` would be better?

File: unfetter-discover-api/api/controllers/x_unfetter_assessments.js (hunk 1 above)
Comment (mushinlogit) [reply unfetter-discover-api/api/controllers/x_unfetter_assessments.js]: you might have a valid point.  still this is a hotfix and would like to minimize frivolous changes outside a functional fix.  additionally one reference to the `courseOfActions` variable might propagate to the client or ui, which would require even more work and testing to change.
no más, no más!?!?

**Review by ghost — APPROVED** [review]
